### ISSUE TITLE
Enable multi language GUI

### ISSUE THREAD

**Issue by bovirus** [agupta231/CARROL#5]
@goobta 

Could be possible to enable multi language GUI?

Thanks.

**Comment by goobta** [comment]
Hi @bovirus!

Unfortunately this was a project for a college class and is no longer maintained. Adding a GUI probably wouldn't do anyone any good as the field has matured so much. In fact, AI-based Super Resolution is so common that Nvidia ships it with their graphics cards!

https://www.nvidia.com/en-us/geforce/technologies/dlss/

If you'd be interested in learning more about Super Resolution, I'd recommend checking out the models & associated papers here:

https://paperswithcode.com/task/image-super-resolution

Sorry for the sad update, but best of luck on your super resolution journey!!

**Comment by bovirus** [comment]
@goobta 

I didn't understand if you are the author of installer that I found on inernet (1.27) 

https://the-sz.com/products/carroll/

Thanks.

**Comment by goobta** [comment]
Hey @bovirus! Yeah, I don't think that's us. This project was for a college class. 

Sorry for the confusion! 
Ankur
